### ISSUE TITLE
EPIC: Build connections for the key EVM wallets

### ISSUE THREAD

**Issue by JBishi** [DefolioTeam/Frontend#2]
-  metamask and two other wallets
-  First start with Metamask and then progress to NEAR
- Initial: Add to top nav component
- Towards end add to WalletConnect modal component 

- [x] #7
- [x] #8
- [x] #9
- [x] #10

**Comment by ashlynlinumlabs** [comment]
Tasks for week of 3rd of July:

- [ ] Connect NEAR wallet selector
- [ ] Flesh out Dashboard widgets
- [ ] Flesh out Portfolio table
- [ ] Stretch goal: Add more Tokens
