### ISSUE TITLE
Epic: Facilitate Multiple Connections Across Chains

### ISSUE THREAD

**Issue by ashlynlinumlabs** [DefolioTeam/Frontend#52]
High level overview of work to be done:

- [ ] Research how one could facilitate multiple concurrent connections across chains
- [ ] Set up Database - Vercel storage solutions, Neo4J and GraphQL, aura DB
- [ ] Add interaction and models for DB into Frontend
- [ ] UI Modal to create portfolio to show multiple wallet connections

End Goal:

Facilitate multiple concurrent connections across chains and accounts AND see all assets in one place on dashboard
